services:
  localstack:
    image: localstack/localstack:3.4.0
    environment:
      - AWS_DEFAULT_REGION=eu-west-1
      - LOCALSTACK_HOST=localstack
      - LS_LOG=warning
      - DISABLE_EVENTS="1"
    ports:
      - 4566:4566
    healthcheck: &healthcheck
      interval: 5s
      retries: 10
      timeout: 10s
      test: 'curl --silent --fail localstack:4566/_localstack/init/ready | grep "completed\": true"'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./e2e/localstack:/etc/localstack/init/ready.d

  status-checker:
    image: public.ecr.aws/lambda/nodejs:20
    volumes:
      - ./dist:/var/task
    environment: &aws_config
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_ACCESS_KEY_ID=testkey
      - AWS_SECRET_ACCESS_KEY=testsecret
      - AWS_REGION=eu-west-1
    ports:
      - 8080:8080
    depends_on:
      localstack:
        condition: service_healthy
    healthcheck:
      <<: *healthcheck
      test: "curl --silent localhost:8080"
    command: handler.check
