service: status-checker

provider:
  name: aws
  runtime: nodejs6.10
  versionFunctions: false
  memorySize: 128
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action: cloudwatch:PutMetricData
      Resource: "*"
    - Effect: Allow
      Action: ssm:GetParameter
      Resource:
        Fn::Join:
          - ":"
          - - arn:aws:ssm
            - Ref: "AWS::Region"
            - Ref: "AWS::AccountId"
            - parameter/services/status-checker/endpoints_base64
    - Effect: "Allow"
      Action: kms:Decrypt
      Resource:
        Fn::Join:
          - ":"
          - - arn:aws:kms
            - Ref: "AWS::Region"
            - Ref: "AWS::AccountId"
            - alias/aws/ssm
functions:
  status_checker:
    handler: handler.check
    description: Check status of endpoints
    environment:
      ENDPOINTS_BASE64_SSM_KEY: /services/status-checker/endpoints_base64
    events:
      - schedule:
          rate: cron(*/5 * * * ? *)
          enabled: true
