AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Check status of endpoints

Resources:
  StatusChecker:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../dist
      Handler: handler.check
      Runtime: nodejs18.x
      Timeout: 900
      Policies:
        - CloudWatchPutMetricPolicy: {}
        - SSMParameterReadPolicy:
            ParameterName: "status-checker/*"

Outputs:
  StatusChecker:
    Value: !GetAtt StatusChecker.Arn
    Export:
      Name: !Sub ${AWS::StackName}-StatusChecker
